apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejsx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejsx
    app.kubernetes.io/part-of: a1
  name: nodejsx
  namespace: christianvogt
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejsx
    weight: 100
status: {}
